<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="carlikebot">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="0.433" /> <!-- arbitrary value for base mass, I think in Kg -->
    <xacro:property name="base_width" value="0.09" />
    <xacro:property name="base_length" value="0.195" />
    <xacro:property name="base_height" value="0.002" />
    <xacro:property name="wheelbase" value="0.145" />
    <xacro:property name="wheel_mass" value="0.024" /> <!-- arbitrary value for wheel mass, I think in Kg -->
    <xacro:property name="wheel_len" value="0.025" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_ygap" value="0.005"/>
    <xacro:property name="wheel_zoff" value="0.0125"/>
    <xacro:property name="wheel_back_xoff" value="0.0775"/>
    <xacro:property name="wheel_front_xoff" value="0.065"/>
    <!-- <xacro:property name="wheeltrack" value="" -->

    <!-- Base Link -->
    <link name="base_link" />

    <!--Base footprint link (it's for slam)-->
    <link name="base_footprint" />

    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Chassis -->

    <link name="chassis_link">
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision> -->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
          <inertia
            ixx="0.000292419" ixy="0.0" ixz="0.0"
            iyy="0.001372213" iyz="0.0"
            izz="0.00166434375"/>
      </inertial>
    </link>

    <joint name="chassis_joint" type="fixed">
      <parent link="base_link"/>
      <child link="chassis_link"/>
      <origin xyz="0 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- IMU sensor -->
    <link name="imu_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.0000001 0.0000001 0.0000001"/>
        </geometry>
        <material name="invisible"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0000001"/>
          <inertia
            ixx="0.0000001" ixy="0.0" ixz="0.0"
            iyy="0.0000001" iyz="0.0"
            izz="0.0000001"/>
      </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="imu_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Ultrasonic sensor -->
    <!-- <link name="ultrasonic_link">
      <visual>
        <origin xyz="0.001 0.001 0.001" rpy="0 0 0"/>
        <geometry>
          <box size="0.0000001 0.0000001 0.0000001"/>
        </geometry>
        <material name="invisible"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0000001"/>
          <inertia
            ixx="0.0000001" ixy="0.0" ixz="0.0"
            iyy="0.0000001" iyz="0.0"
            izz="0.0000001"/>
      </inertial>
    </link>

    <joint name="ultrasonic_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="ultrasonic_link"/>
      <origin xyz="0.0 0.0 0.12" rpy="0 0 0"/>
    </joint> -->

    <!-- Camera sensor -->
    <!-- <link name="camera_link">
      <visual>
        <origin xyz="0.002 0.002 0.002" rpy="0 0 0"/>
        <geometry>
          <box size="0.0000001 0.0000001 0.0000001"/>
        </geometry>
        <material name="invisible"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0000001"/>
          <inertia
            ixx="0.0000001" ixy="0.0" ixz="0.0"
            iyy="0.0000001" iyz="0.0"
            izz="0.0000001"/>
      </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="camera_link"/>
      <origin xyz="0.0 0.0 0.2" rpy="0 0 0"/>
    </joint> -->

    <!-- Lidar sensor -->
    <link name="lidar_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.125"/>
        <inertia ixx="0.000001"  ixy="0"  ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.01" length="0.01"/>
        </geometry>
      </visual>
    </link>

    <joint name="lidar_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="lidar_link"/>
      <origin xyz="0 0 0.12" rpy="0 0 0"/>
    </joint>

    <!-- rear wheels -->

    <!-- virtual rear wheel -->

    <link name="virtual_rear_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.0000075875" ixy="0.0" ixz="0.0"
          iyy="0.0000075875" iyz="0.0"
          izz="0.000012675"/>
      </inertial>
    </link>

    <joint name="virtual_rear_wheel_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="virtual_rear_wheel"/>
      <origin xyz="-${wheel_back_xoff} 0 -${wheel_zoff}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <!-- <dynamics damping="0.2"/> -->
    </joint>

    <!-- rear right wheel -->

    <link name="rear_right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.0000075875" ixy="0.0" ixz="0.0"
          iyy="0.0000075875" iyz="0.0"
          izz="0.000012675"/>
      </inertial>

    </link>

    <joint name="rear_right_wheel_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="rear_right_wheel"/>
      <origin xyz="-${wheel_back_xoff} -${base_width/2+wheel_ygap+wheel_len/2} -${wheel_zoff}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <!-- <dynamics damping="0.2"/> -->
      <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <!-- rear left wheel -->
    <link name="rear_left_wheel">
        <collision>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
          </geometry>
          <material name="black"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <mass value="${wheel_mass}"/>
          <inertia
            ixx="0.0000075875" ixy="0.0" ixz="0.0"
            iyy="0.0000075875" iyz="0.0"
            izz="0.000012675"/>
        </inertial>

    </link>

    <joint name="rear_left_wheel_joint" type="continuous">
      <parent link="chassis_link" />
      <child link="rear_left_wheel" />
      <origin xyz="-${wheel_back_xoff} ${base_width/2+wheel_ygap+wheel_len/2} -${wheel_zoff}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <!-- <dynamics damping="0.2"/> -->
      <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <!-- front wheels -->

    <!-- virtual front wheel -->

    <link name="virtual_front_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.0000075875" ixy="0.0" ixz="0.0"
          iyy="0.0000075875" iyz="0.0"
          izz="0.000012675"/>
      </inertial>
    </link>

    <joint name="virtual_front_wheel_joint" type="revolute">
      <parent link="chassis_link"/>
      <child link="virtual_front_wheel"/>
      <origin xyz="${wheel_front_xoff} 0 -${wheel_zoff}" rpy="0 0 ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
    </joint>

    <!-- front right wheel -->


    <link name="front_right_wheel">

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.0000075875" ixy="0.0" ixz="0.0"
          iyy="0.0000075875" iyz="0.0"
          izz="0.000012675"/>
      </inertial>
    </link>

    <joint name="front_right_wheel_joint" type="continuous">
      <parent link="chassis_link" />
      <child link="front_right_wheel" />
      <origin xyz="${wheel_front_xoff} -${base_width/2+wheel_ygap+wheel_len/2} -${wheel_zoff}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <!-- front left steering -->


    <link name="front_left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.0000075875" ixy="0.0" ixz="0.0"
          iyy="0.0000075875" iyz="0.0"
          izz="0.000012675"/>
      </inertial>

    </link>

    <joint name="front_left_wheel_joint" type="continuous">
      <parent link="chassis_link" />
      <child link="front_left_wheel" />
      <origin xyz="${wheel_front_xoff} ${base_width/2+wheel_ygap+wheel_len/2} -${wheel_zoff}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

  </xacro:macro>

</robot>