<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="carlikebot" >

    <!-- Define robot constants -->
    <xacro:property name="base_width" value="0.09"/>
    <xacro:property name="base_length" value="0.195"/>
    <xacro:property name="base_height" value="0.002"/>

    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_ygap" value="0.005"/>
    <xacro:property name="wheel_zoff" value="0.0125"/>
    <xacro:property name="wheel_back_xoff" value="0.0775"/>
    <xacro:property name="wheel_front_xoff" value="0.065"/>
    <xacro:property name="wheelbase" value="0.145"/>

    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
    </link>

    <!-- Robot Footprint -->
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>

    <!-- Virtual Wheels -->
    <xacro:macro name="virtual_wheel" params="prefix x_reflect">
        <link name="virtual_${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <material name="Invisible">
                    <color rgba="0.0 0.0 0.0 0.0"/>
                </material>
            </visual>
        </link>

        <xacro:if value="${x_reflect == -1}">
            <xacro:property name="joint_type" value="continuous"/>
        </xacro:if>

        <xacro:if value="${x_reflect == 1}">
            <xacro:property name="joint_type" value="revolute"/>
        </xacro:if>

        <joint name="virtual_${prefix}_wheel_joint" type="${joint_type}">
            <parent link="base_link"/>
            <child link="virtual_${prefix}_wheel"/>
            <origin xyz="${x_reflect*wheelbase/2} 0 -${base_height/2}" rpy="0 0 0"/>
            <xacro:if value="${x_reflect == -1}">
                <axis xyz="1 0 0"/>
                <limit effort="100.0" velocity="100.0"/>
            </xacro:if>
            <xacro:if value="${x_reflect == 1}">
                <axis xyz="0 0 1"/>
                <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
            </xacro:if>
        </joint>
    </xacro:macro>

    <xacro:virtual_wheel prefix="rear" x_reflect="-1" />
    <xacro:virtual_wheel prefix="front" x_reflect="1" />

    <!-- Real Wheels -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link">
            <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="Gray">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
            </visual>
        </link>

        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <xacro:if value="${x_reflect == -1}">
                <origin xyz="${x_reflect*wheel_back_xoff} ${y_reflect*(base_width/2+wheel_ygap+wheel_width/2)} ${-wheel_zoff}" rpy="0 0 0"/>
                <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
            </xacro:if>
            <xacro:if value="${x_reflect == 1}">
                <origin xyz="${wheel_front_xoff} ${y_reflect*(base_width/2+wheel_ygap+wheel_width/2)} ${-wheel_zoff}" rpy="0 0 0"/>
                <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/>
            </xacro:if>
            <axis xyz="0 1 0"/>
        </joint>

    </xacro:macro>

    <xacro:wheel prefix="backwhl_l" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="backwhl_r" x_reflect="-1" y_reflect="-1" />
    <xacro:wheel prefix="frontwhl_l" x_reflect="1" y_reflect="1" />
    <xacro:wheel prefix="frontwhl_r" x_reflect="1" y_reflect="-1" />

    </xacro:macro>

</robot>