controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController


diffbot_base_controller:
  ros__parameters:
    wheel_separation: 0.13
    wheel_radius: 0.0325
    left_wheel_names: ["front_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint"]
    open_loop: false
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    use_stamped_vel: false
    state_publish_rate: 100.0

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id:  "imu_link"
    static_covariance_orientation: [0.01, 0.000, 0.000, 0.000, 0.01, 0.000, 0.000, 0.000, 0.01]
    static_covariance_angular_velocity: [0.01, 0.000, 0.000, 0.000, 0.01, 0.000, 0.000, 0.000, 0.01]
    static_covariance_linear_acceleration: [0.01, 0.000, 0.000, 0.000, 0.01, 0.000, 0.000, 0.000, 0.01]