controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController


diffbot_base_controller:
  ros__parameters:
    # wheelbase: 0.145
    # front_wheel_radius: 0.0325
    # rear_wheel_radius: 0.0325
    # front_steering: true
    # reference_timeout: 2.0
    # rear_wheels_names: ['virtual_rear_wheel_joint']
    # front_wheels_names: ['virtual_front_wheel_joint']
    # open_loop: false
    # velocity_rolling_window_size: 10
    # base_frame_id: base_link
    # odom_frame_id: odom
    # enable_odom_tf: true
    # twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    # pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    # position_feedback: false
    # # use_stamped_vel: true
    # use_stamped_vel: false
    # state_publish_rate: 100.0

    wheel_separation: 0.13
    wheel_radius: 0.0325
    left_wheel_names: ["front_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint"]
    open_loop: true
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    use_stamped_vel: false
    state_publish_rate: 100.0

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id:  "imu_link"